SERVER_URL = "https://0d2c-5-195-250-105.in.ngrok.io"

def createPdf(data,fileName,user =None):
    # Import FPDF class
    from ctypes import alignment
    from fpdf import FPDF
    
    # Create instance of FPDF class
    # Letter size paper, use inches as unit of measure
    pdf=FPDF(format='letter', unit='in')
    # Add new page. Without this you cannot create the document.
    pdf.add_page()
    
    # Remember to always put one of these at least once.
    pdf.set_font('Times','',10.0) 
    
    # Effective page width, or just epw
    epw = pdf.w - 2*pdf.l_margin
    
    # Set column width to 1/4 of effective page width to distribute content 
    # evenly across table and page
    col_width = epw/8
    
    # Since we do not need to draw lines anymore, there is no need to separate
    # headers from data matrix.
    
    
    pdf.image("./assets/img/nsp-logo-full.jpeg", x = None, y =None, w = 2, h = 1)
    from qr import QR
    QR(SERVER_URL+"/assets/pdf/"+fileName+".pdf")
    pdf.image("./assets/img/qr.png",x=7,y=2,w=1,h=1)
    # Document title centered, 'B'old, 14 pt
    pdf.set_font('Times','B',18.0) 
    pdf.set_text_color(200,10,10)
    pdf.cell(epw, 0.0, 'Nonstop Payments Providers LLC.', align='C')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.3)
    pdf.set_text_color(128,128,128)
    pdf.set_font('Times','B',15.0) 
    pdf.cell(epw, 0.0, 'Transactions Summary', align='C')
    pdf.set_font('Times','',10.0) 
    pdf.ln(1)
    pdf.set_text_color(0,0,0)

    from main import getCurrentTimeStamp
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'Generated On : '+getCurrentTimeStamp(), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)

    if user is not None:
        pdf.set_font('Times','IB',10.0) 
        pdf.set_text_color(0,100,0)
        pdf.cell(epw, 0.0, 'Generated By : '+user, align='L')
        pdf.set_font('Times','',10.0) 
        pdf.set_text_color(0,0,0)
        pdf.ln(0.2)
       
    # Text height is the same as current font size
    th = pdf.font_size
    headers = [['TID','Reciept #','Date','Time','Service','User','Amount','Pending']]
    for row in headers:
        for datum in row:
            
            if datum == row[0]:
                pdf.set_font('Times','B',10) 
                pdf.cell(col_width+0.2, 2*th, str(datum), border=1,align='C')
            else:
                pdf.set_font('Times','B',10) 
                pdf.cell(col_width, 2*th, str(datum), border=1,align='C')
        pdf.ln(2*th)

    tt = 0
    tpd = 0
    tpn  = 0
    tpt = 0
    for row in data:
        for i in row:
            pdf.set_text_color(0,0,0)
            if i == row[0]:
                pdf.set_font('Times','I',8.1)        
                pdf.cell(col_width+0.2, 2*th, str(i), border=1,align='C')
            elif i == row[4]:
                pdf.set_font('Times','',10) 
                pdf.set_text_color(0,100,0)
                pdf.cell(col_width, 2*th, str(i), border=1,align='C')
            else:
                pdf.set_font('Times','',10) 
                pdf.cell(col_width, 2*th, str(i), border=1,align='C')
        tt = tt+int(row[6])
        tpn = tpn + int(row[7])
        if int(row[7]) > 0:
            tpt = tpt+1

        pdf.ln(2*th)
    tp = tt- tpn
    pdf.ln(0.6)
    pdf.set_font('Times','B',12.0) 
    pdf.cell(epw, 0.0, "Total Transactions : "+str(len(data)), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','B',12.0) 
    pdf.cell(epw, 0.0, "Total Pending Transactions : "+str(tpt), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','BI',12.0) 
    pdf.set_text_color(255,0,0)
    pdf.cell(epw, 0.0, "Total : "+str(tt)+" AED", align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','BI',12.0) 
    pdf.cell(epw, 0.0, "Total Pending : "+str(tpn)+" AED", align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','BI',12.0) 
    pdf.cell(epw, 0.0, "Total Amound Paid: "+str(tp)+" AED", align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.output("./assets/pdf/"+fileName+'.pdf','F')
    return fileName+".pdf"

def createVoucherPdf(data,fileName,user =None):
    # Import FPDF class
    from ctypes import alignment
    from fpdf import FPDF
    
    # Create instance of FPDF class
    # Letter size paper, use inches as unit of measure
    pdf=FPDF(format='letter', unit='in')
    # Add new page. Without this you cannot create the document.
    pdf.add_page()
    
    # Remember to always put one of these at least once.
    pdf.set_font('Times','',10.0) 
    
    # Effective page width, or just epw
    epw = pdf.w - 2*pdf.l_margin
    
    # Set column width to 1/4 of effective page width to distribute content 
    # evenly across table and page
    col_width = epw/8
    
    # Since we do not need to draw lines anymore, there is no need to separate
    # headers from data matrix.
    

    pdf.image("./assets/img/nsp-logo-full.jpeg", x = None, y =None, w = 2, h = 1)
    from qr import QR
    QR(SERVER_URL+"/assets/pdf/"+fileName+".pdf")
    pdf.image("./assets/img/qr.png",x=7,y=2,w=1,h=1)
    # Document title centered, 'B'old, 14 pt
    pdf.set_font('Times','B',18.0) 
    pdf.set_text_color(200,10,10)
    pdf.cell(epw, 0.0, 'Nonstop Payments Providers LLC.', align='C')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.3)
    pdf.set_text_color(128,128,128)
    pdf.set_font('Times','B',15.0) 
    pdf.cell(epw, 0.0, 'Vouchers Summary', align='C')
    pdf.set_font('Times','',10.0) 
    pdf.ln(1)
    pdf.set_text_color(0,0,0)
    '''
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'From : 03-Jun-2022', align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'To : 03-Jul-2022', align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    '''
    from main import getCurrentTimeStamp
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'Generated On : '+getCurrentTimeStamp(), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)

    if user is not None:
        pdf.set_font('Times','IB',10.0) 
        pdf.set_text_color(0,100,0)
        pdf.cell(epw, 0.0, 'Generated By : '+user, align='L')
        pdf.set_font('Times','',10.0) 
        pdf.set_text_color(0,0,0)
        pdf.ln(0.2)
        
    # Text height is the same as current font size
    th = pdf.font_size
    headers = [['TID','Reciept #','Date','Time','Plan','Site','PIN','Total']]
    for row in headers:
        for datum in row:
            if datum == row[0]:
                pdf.set_font('Times','B',10) 
                pdf.cell(col_width+0.2, 2*th, str(datum), border=1,align='C')
            else:
                pdf.set_font('Times','B',10) 
                pdf.cell(col_width, 2*th, str(datum), border=1,align='C')
        pdf.ln(2*th)
    tt = 0
    tpn  = 0
    for row in data:
        for i in row:
            if i == row[0]:
                pdf.set_font('Times','I',8.1)        
                pdf.cell(col_width+0.2, 2*th, str(i), border=1,align='C')
            else:
                pdf.set_font('Times','',10) 
                pdf.cell(col_width, 2*th, str(i), border=1,align='C')
        tt = tt+int(row[7])
        pdf.ln(2*th)
    tp = tt- tpn
    pdf.ln(0.6)
    pdf.set_font('Times','B',12.0) 
    pdf.cell(epw, 0.0, "Total Vouhcers : "+str(len(data)), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','BI',12.0) 
    pdf.set_text_color(255,0,0)
    pdf.cell(epw, 0.0, "Total : "+str(tt)+" AED", align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.output("./assets/pdf/"+fileName+'.pdf','F')
    return fileName+".pdf"


def createTerminalPdf(data,fileName,user =None):
    # Import FPDF class
    from ctypes import alignment
    from fpdf import FPDF
    
    # Create instance of FPDF class
    # Letter size paper, use inches as unit of measure
    pdf=FPDF(format='letter', unit='in')
    # Add new page. Without this you cannot create the document.
    pdf.add_page()
    
    # Remember to always put one of these at least once.
    pdf.set_font('Times','',10.0) 
    
    # Effective page width, or just epw
    epw = pdf.w - 2*pdf.l_margin
    
    # Set column width to 1/4 of effective page width to distribute content 
    # evenly across table and page
    col_width = epw/5
    
    # Since we do not need to draw lines anymore, there is no need to separate
    # headers from data matrix.
    

    pdf.image("./assets/img/nsp-logo-full.jpeg", x = None, y =None, w = 2, h = 1)
    from qr import QR
    QR(SERVER_URL+"/assets/pdf/"+fileName+".pdf")
    pdf.image("./assets/img/qr.png",x=7,y=2,w=1,h=1)
    # Document title centered, 'B'old, 14 pt
    pdf.set_font('Times','B',18.0) 
    pdf.set_text_color(200,10,10)
    pdf.cell(epw, 0.0, 'Nonstop Payments Providers LLC.', align='C')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.3)
    pdf.set_text_color(128,128,128)
    pdf.set_font('Times','B',15.0) 
    pdf.cell(epw, 0.0, 'Terminals Summary', align='C')
    pdf.set_font('Times','',10.0) 
    pdf.ln(1)
    pdf.set_text_color(0,0,0)
    '''
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'From : 03-Jun-2022', align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'To : 03-Jul-2022', align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    '''
    from main import getCurrentTimeStamp
    pdf.set_font('Times','B',10.0) 
    pdf.cell(epw, 0.0, 'Generated On : '+getCurrentTimeStamp(), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)

    if user is not None:
        pdf.set_font('Times','IB',10.0) 
        pdf.set_text_color(0,100,0)
        pdf.cell(epw, 0.0, 'Generated By : '+user, align='L')
        pdf.set_font('Times','',10.0) 
        pdf.set_text_color(0,0,0)
        pdf.ln(0.2)
        
    # Text height is the same as current font size
    th = pdf.font_size
    headers = [['Terminal Serial','Site #','Site Name','Status','Stacker']]
    for row in headers:
        for datum in row:
            if datum == row[0]:
                pdf.set_font('Times','B',10) 
                pdf.cell(col_width+0.2, 2*th, str(datum), border=1,align='C')
            else:
                pdf.set_font('Times','B',10) 
                pdf.cell(col_width, 2*th, str(datum), border=1,align='C')
        pdf.ln(2*th)
    t_on = 0
    t_off = 0
    for row in data:
        for i in row:
            if i == row[0]:
                pdf.set_font('Times','I',8.1)        
                pdf.cell(col_width+0.2, 2*th, str(i), border=1,align='C')
            else:
                pdf.set_font('Times','',10) 
                pdf.cell(col_width, 2*th, str(i), border=1,align='C')
        if  row[3] == "on":
            t_on = t_on +1
        elif row[3] == "off":
            t_off = t_off +1
        pdf.ln(2*th)
    pdf.ln(0.6)
    pdf.set_font('Times','B',12.0) 
    pdf.cell(epw, 0.0, "Total Terminals : "+str(len(data)), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','BI',12.0) 
    pdf.set_text_color(255,0,0)
    pdf.cell(epw, 0.0, "Active Terminals : "+str(t_on), align='L')
    pdf.set_font('Times','',10.0) 
    pdf.ln(0.2)
    pdf.set_font('Times','BI',12.0) 
    pdf.cell(epw, 0.0, "UnActive Terminals : "+str(t_off), align='L')
    pdf.set_font('Times','BI',12.0) 
    pdf.ln(0.2)
    pdf.output("./assets/pdf/"+fileName+'.pdf','F')
    return fileName+".pdf"